//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShoppingEntities : DbContext
    {
        public ShoppingEntities()
            : base("name=ShoppingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorytbl> Categorytbls { get; set; }
        public virtual DbSet<Product_tbl> Product_tbl { get; set; }
    
        public virtual ObjectResult<Nullable<int>> USER_LOG(string cust_name, string cust_password, string cust_email)
        {
            var cust_nameParameter = cust_name != null ?
                new ObjectParameter("cust_name", cust_name) :
                new ObjectParameter("cust_name", typeof(string));
    
            var cust_passwordParameter = cust_password != null ?
                new ObjectParameter("cust_password", cust_password) :
                new ObjectParameter("cust_password", typeof(string));
    
            var cust_emailParameter = cust_email != null ?
                new ObjectParameter("cust_email", cust_email) :
                new ObjectParameter("cust_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USER_LOG", cust_nameParameter, cust_passwordParameter, cust_emailParameter);
        }
    
        public virtual int Ins_User_tbl(string cust_name, string cust_password, string cust_email)
        {
            var cust_nameParameter = cust_name != null ?
                new ObjectParameter("cust_name", cust_name) :
                new ObjectParameter("cust_name", typeof(string));
    
            var cust_passwordParameter = cust_password != null ?
                new ObjectParameter("cust_password", cust_password) :
                new ObjectParameter("cust_password", typeof(string));
    
            var cust_emailParameter = cust_email != null ?
                new ObjectParameter("cust_email", cust_email) :
                new ObjectParameter("cust_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ins_User_tbl", cust_nameParameter, cust_passwordParameter, cust_emailParameter);
        }
    }
}
